---
version: '3'
services:
  jenkins:
    build:
      context: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      JENKINS_LOCATION_URL: ${JENKINS_LOCATION_URL:-http://localhost:8080/}
  swarm:
    build:
      context: swarm-from-docker
    environment:
      MASTER: ${JENKINS_LOCATION_URL:-http://localhost:8080}
      USERNAME: admin
      PASSWORD: admin
